/**
 * TvSerialsLiveScraper.js
 * High-performance Scraper & Resolver for Tamil TV Serials
 * Supports:
 * - Server 1 (tamildhool.tech)
 * - Server 2 (arivumani.net / playallu.xyz)
 */

import axios from 'axios';

// Available Tamil Serials with Real Poster Images
export const COMPREHENSIVE_ALL_SERIALS = [
  {
    "id": "sun_kayal",
    "serialCode": "kayal",
    "title": "Kayal",
    "tamilTitle": "கயல்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "07:30 PM",
    "episodes": "1240+ Eps",
    "episodesCount": "1240 episodes logged",
    "category": "serial",
    "tag": "Daily Soap",
    "networkTag": "SUN TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/Kayal.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_singapennae",
    "serialCode": "singapennae",
    "title": "Singapennae",
    "tamilTitle": "சிங்கப்பெண்ணே",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "08:00 PM",
    "episodes": "540+ Eps",
    "episodesCount": "540 episodes logged",
    "category": "serial",
    "tag": "Prime Slot",
    "networkTag": "SUN TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/Singappenn.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_vanathai_pola",
    "serialCode": "vanathai_pola",
    "title": "Vanathai Pola",
    "tamilTitle": "வானத்தை போல",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "06:30 PM",
    "episodes": "1150+ Eps",
    "episodesCount": "1150 episodes logged",
    "category": "serial",
    "tag": "Family Drama",
    "networkTag": "SUN TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/vanathai.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_marumagal",
    "serialCode": "marumagal",
    "title": "Marumagal",
    "tamilTitle": "மருமகள்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "07:00 PM",
    "episodes": "380+ Eps",
    "episodesCount": "380 episodes logged",
    "category": "serial",
    "tag": "Daily Soap",
    "networkTag": "SUN TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/marumagal.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_moondru_mudichu",
    "serialCode": "moondru_mudichu",
    "title": "Moondru Mudichu",
    "tamilTitle": "மூன்று முடிச்சு",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "08:30 PM",
    "episodes": "290+ Eps",
    "episodesCount": "290 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "SUN TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/Moondru.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_annam",
    "serialCode": "annam",
    "title": "Annam",
    "tamilTitle": "அன்னம்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "01:30 PM",
    "episodes": "310+ Eps",
    "episodesCount": "310 episodes logged",
    "category": "serial",
    "tag": "Afternoon Special",
    "networkTag": "SUN TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/annam.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_lakshmi",
    "serialCode": "lakshmi",
    "title": "Lakshmi",
    "tamilTitle": "லட்சுமி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "09:00 PM",
    "episodes": "420+ Eps",
    "episodesCount": "420 episodes logged",
    "category": "serial",
    "tag": "Prime Hit",
    "networkTag": "SUN TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/Lakshmi.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_thulasi",
    "serialCode": "thulasi",
    "title": "Thulasi",
    "tamilTitle": "துளசி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "02:00 PM",
    "episodes": "260+ Eps",
    "episodesCount": "260 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "SUN TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2026/05/thu.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_sundari",
    "serialCode": "sundari",
    "title": "Sundari",
    "tamilTitle": "சுந்தரி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "09:30 PM",
    "episodes": "1020+ Eps",
    "episodesCount": "1020 episodes logged",
    "category": "serial",
    "tag": "Inspirational",
    "networkTag": "SUN TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sundari.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_sevvanthi",
    "serialCode": "sevvanthi",
    "title": "Sevvanthi",
    "tamilTitle": "செவ்வந்தி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "12:30 PM",
    "episodes": "780+ Eps",
    "episodesCount": "780 episodes logged",
    "category": "serial",
    "tag": "Noon Soap",
    "networkTag": "SUN TV • DAILY",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sevvanthi.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_ilakkiya",
    "serialCode": "ilakkiya",
    "title": "Ilakkiya",
    "tamilTitle": "இலக்கியா",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "01:00 PM",
    "episodes": "650+ Eps",
    "episodesCount": "650 episodes logged",
    "category": "serial",
    "tag": "Daily Soap",
    "networkTag": "SUN TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/ilakkiya.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_iniya",
    "serialCode": "iniya",
    "title": "Iniya",
    "tamilTitle": "இனிய",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "10:00 PM",
    "episodes": "590+ Eps",
    "episodesCount": "590 episodes logged",
    "category": "serial",
    "tag": "Night Soap",
    "networkTag": "SUN TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/iniya.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_poonkodi",
    "serialCode": "poonkodi",
    "title": "Poonkodi",
    "tamilTitle": "பூங்கொடி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "01:00 PM",
    "episodes": "160+ Eps",
    "episodesCount": "160 episodes logged",
    "category": "serial",
    "tag": "Afternoon Drama",
    "networkTag": "SUN TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/pk.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_mr_manaivi",
    "serialCode": "mr_manaivi",
    "title": "Mr. Manaivi",
    "tamilTitle": "மிஸ்டர் மனைவி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "08:30 PM",
    "episodes": "420+ Eps",
    "episodesCount": "420 episodes logged",
    "category": "serial",
    "tag": "Family Entertainer",
    "networkTag": "SUN TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/mm.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_malar",
    "serialCode": "malar",
    "title": "Malar",
    "tamilTitle": "மலர்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "03:30 PM",
    "episodes": "380+ Eps",
    "episodesCount": "380 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "SUN TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/malar.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "sun_priyamaana_thozhi",
    "serialCode": "priyamaana_thozhi",
    "title": "Priyamaana Thozhi",
    "tamilTitle": "பிரியமான தோழி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "timeSlot": "04:00 PM",
    "episodes": "510+ Eps",
    "episodesCount": "510 episodes logged",
    "category": "serial",
    "tag": "Friendship Drama",
    "networkTag": "SUN TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/pt.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "vijay_siragadikka_aasai",
    "serialCode": "siragadikka_aasai",
    "title": "Siragadikka Aasai",
    "tamilTitle": "சிறகடிக்க ஆசை",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "09:00 PM",
    "episodes": "480+ Eps",
    "episodesCount": "480 episodes logged",
    "category": "serial",
    "tag": "Top TRP",
    "networkTag": "VIJAY TV • TRENDING",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sirshu.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_baakiyalakshmi",
    "serialCode": "baakiyalakshmi",
    "title": "Baakiyalakshmi",
    "tamilTitle": "பாக்கியலட்சுமி",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "08:30 PM",
    "episodes": "1350+ Eps",
    "episodesCount": "1350 episodes logged",
    "category": "serial",
    "tag": "Prime Slot",
    "networkTag": "VIJAY TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/baakiya.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_pandian_stores_2",
    "serialCode": "pandian_stores_2",
    "title": "Pandian Stores 2",
    "tamilTitle": "பாண்டியன் ஸ்டோர்ஸ் 2",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "08:00 PM",
    "episodes": "340+ Eps",
    "episodesCount": "340 episodes logged",
    "category": "serial",
    "tag": "Family Saga",
    "networkTag": "VIJAY TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/pandian.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_mahanathi",
    "serialCode": "mahanathi",
    "title": "Mahanathi",
    "tamilTitle": "மகாநதி",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "07:00 PM",
    "episodes": "510+ Eps",
    "episodesCount": "510 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/mahanadhi.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_aaha_kalyanam",
    "serialCode": "aaha_kalyanam",
    "title": "Aaha Kalyanam",
    "tamilTitle": "ஆஹா கல்யாணம்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "07:30 PM",
    "episodes": "420+ Eps",
    "episodesCount": "420 episodes logged",
    "category": "serial",
    "tag": "Romantic Drama",
    "networkTag": "VIJAY TV • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/aaha.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_modhalum_kaadhalum",
    "serialCode": "modhalum_kaadhalum",
    "title": "Modhalum Kaadhalum",
    "tamilTitle": "மோதலும் காதலும்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "06:30 PM",
    "episodes": "390+ Eps",
    "episodesCount": "390 episodes logged",
    "category": "serial",
    "tag": "Youth Romance",
    "networkTag": "VIJAY TV • ROMANCE",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/modhalum.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_malli",
    "serialCode": "malli",
    "title": "Malli",
    "tamilTitle": "மல்லி",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "06:00 PM",
    "episodes": "210+ Eps",
    "episodesCount": "210 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://arivumani.net/wp-content/uploads/2025/11/malli-230x150.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_chinna_marumagal",
    "serialCode": "chinna_marumagal",
    "title": "Chinna Marumagal",
    "tamilTitle": "சின்ன மருமகள்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "09:30 PM",
    "episodes": "290+ Eps",
    "episodesCount": "290 episodes logged",
    "category": "serial",
    "tag": "Prime Soap",
    "networkTag": "VIJAY TV • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/chinna.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_thendrale_mella_pesu",
    "serialCode": "thendrale_mella_pesu",
    "title": "Thendrale Mella Pesu",
    "tamilTitle": "தென்றலே மெல்ல பேசு",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "03:00 PM",
    "episodes": "140+ Eps",
    "episodesCount": "140 episodes logged",
    "category": "serial",
    "tag": "Romantic Drama",
    "networkTag": "VIJAY TV • SPECIAL",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/TMP.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_ayyanar_thunai",
    "serialCode": "ayyanar_thunai",
    "title": "Ayyanar Thunai",
    "tamilTitle": "அய்யனார் துணை",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "02:30 PM",
    "episodes": "120+ Eps",
    "episodesCount": "120 episodes logged",
    "category": "serial",
    "tag": "Devotional Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/ayy.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_azhagae_azhagu",
    "serialCode": "azhagae_azhagu",
    "title": "Azhagae Azhagu",
    "tamilTitle": "அழகே அழகு",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "02:00 PM",
    "episodes": "110+ Eps",
    "episodesCount": "110 episodes logged",
    "category": "serial",
    "tag": "Family Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/aa.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_thaai_maaman",
    "serialCode": "thaai_maaman",
    "title": "Thaai Maaman",
    "tamilTitle": "தாய் மாமன்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "01:30 PM",
    "episodes": "95+ Eps",
    "episodesCount": "95 episodes logged",
    "category": "serial",
    "tag": "Village Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/tm.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_sakthivel",
    "serialCode": "sakthivel",
    "title": "Sakthivel",
    "tamilTitle": "சக்திவேல்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "01:00 PM",
    "episodes": "160+ Eps",
    "episodesCount": "160 episodes logged",
    "category": "serial",
    "tag": "Action Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sakthivel.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_ponni",
    "serialCode": "ponni",
    "title": "Ponni",
    "tamilTitle": "பொன்னி",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "03:30 PM",
    "episodes": "390+ Eps",
    "episodesCount": "390 episodes logged",
    "category": "serial",
    "tag": "Emotional Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/ponni.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_nee_naan_kaadhal",
    "serialCode": "nee_naan_kaadhal",
    "title": "Nee Naan Kaadhal",
    "tamilTitle": "நீ நான் காதல்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "03:00 PM",
    "episodes": "240+ Eps",
    "episodesCount": "240 episodes logged",
    "category": "serial",
    "tag": "Youth Romance",
    "networkTag": "VIJAY TV • ROMANCE",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/neenaan.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "vijay_thangamagal",
    "serialCode": "thangamagal",
    "title": "Thangamagal",
    "tamilTitle": "தங்கமகள்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "timeSlot": "03:30 PM",
    "episodes": "220+ Eps",
    "episodesCount": "220 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "VIJAY TV • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/thangamagal.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "zee_karthigai_deepam",
    "serialCode": "karthigai_deepam",
    "title": "Karthigai Deepam",
    "tamilTitle": "கார்த்திகை தீபம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "08:00 PM",
    "episodes": "510+ Eps",
    "episodesCount": "510 episodes logged",
    "category": "serial",
    "tag": "Daily Soap",
    "networkTag": "ZEE TAMIL • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/kd1.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_sandhya_raagam",
    "serialCode": "sandhya_raagam",
    "title": "Sandhya Raagam",
    "tamilTitle": "சந்தியா ராகம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "07:30 PM",
    "episodes": "430+ Eps",
    "episodesCount": "430 episodes logged",
    "category": "serial",
    "tag": "Emotional Drama",
    "networkTag": "ZEE TAMIL • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sr1.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_ayali",
    "serialCode": "ayali",
    "title": "Ayali",
    "tamilTitle": "அயலி",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "06:30 PM",
    "episodes": "160+ Eps",
    "episodesCount": "160 episodes logged",
    "category": "serial",
    "tag": "Inspiring Drama",
    "networkTag": "ZEE TAMIL • SPECIAL",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/ayali1.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_thirumangalyam",
    "serialCode": "thirumangalyam",
    "title": "Thirumangalyam",
    "tamilTitle": "திருமாங்கல்யம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "07:00 PM",
    "episodes": "220+ Eps",
    "episodesCount": "220 episodes logged",
    "category": "serial",
    "tag": "Family Drama",
    "networkTag": "ZEE TAMIL • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/tm.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_samanthi",
    "serialCode": "samanthi",
    "title": "Samanthi",
    "tamilTitle": "சாமந்தி",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "08:30 PM",
    "episodes": "190+ Eps",
    "episodesCount": "190 episodes logged",
    "category": "serial",
    "tag": "Daily Drama",
    "networkTag": "ZEE TAMIL • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/samanthi.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_vaagai_sooda_vaa",
    "serialCode": "vaagai_sooda_vaa",
    "title": "Vaagai Sooda Vaa",
    "tamilTitle": "வாகை சூட வா",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "09:00 PM",
    "episodes": "120+ Eps",
    "episodesCount": "120 episodes logged",
    "category": "serial",
    "tag": "High TRP",
    "networkTag": "ZEE TAMIL • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2026/01/vaa.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_vasudha",
    "serialCode": "vasudha",
    "title": "Vasudha",
    "tamilTitle": "வசுதா",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "09:30 PM",
    "episodes": "75+ Eps",
    "episodesCount": "75 episodes logged",
    "category": "serial",
    "tag": "New Prime Soap",
    "networkTag": "ZEE TAMIL • NEW",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2026/09/vaasu.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_parijatham",
    "serialCode": "parijatham",
    "title": "Parijatham",
    "tamilTitle": "பாரிஜாதம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "06:00 PM",
    "episodes": "280+ Eps",
    "episodesCount": "280 episodes logged",
    "category": "serial",
    "tag": "Evening Soap",
    "networkTag": "ZEE TAMIL • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/09/pj2.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_salangai_oli",
    "serialCode": "salangai_oli",
    "title": "Salangai Oli",
    "tamilTitle": "சலங்கை ஒலி",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "01:30 PM",
    "episodes": "160+ Eps",
    "episodesCount": "160 episodes logged",
    "category": "serial",
    "tag": "Dance Drama",
    "networkTag": "ZEE TAMIL • NOON",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/08/so.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_puthu_vasantham",
    "serialCode": "puthu_vasantham",
    "title": "Puthu Vasantham",
    "tamilTitle": "புது வசந்தம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "02:00 PM",
    "episodes": "240+ Eps",
    "episodesCount": "240 episodes logged",
    "category": "serial",
    "tag": "Family Soap",
    "networkTag": "ZEE TAMIL • NOON",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/Puthu.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_idhayam",
    "serialCode": "idhayam",
    "title": "Idhayam",
    "tamilTitle": "இதயம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "01:00 PM",
    "episodes": "390+ Eps",
    "episodesCount": "390 episodes logged",
    "category": "serial",
    "tag": "Emotional Drama",
    "networkTag": "ZEE TAMIL • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/id1.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_varisu",
    "serialCode": "varisu",
    "title": "Varisu",
    "tamilTitle": "வாரிசு",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "02:30 PM",
    "episodes": "190+ Eps",
    "episodesCount": "190 episodes logged",
    "category": "serial",
    "tag": "Family Legacy",
    "networkTag": "ZEE TAMIL • DRAMA",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/vari.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_veera",
    "serialCode": "veera",
    "title": "Veera",
    "tamilTitle": "வீரா",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "08:00 PM",
    "episodes": "310+ Eps",
    "episodesCount": "310 episodes logged",
    "category": "serial",
    "tag": "Bravery Saga",
    "networkTag": "ZEE TAMIL • PRIME",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/veera.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_meenakshi_ponnunga",
    "serialCode": "meenakshi_ponnunga",
    "title": "Meenakshi Ponnunga",
    "tamilTitle": "மீனாட்சி பொண்ணுங்க",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "09:30 PM",
    "episodes": "650+ Eps",
    "episodesCount": "650 episodes logged",
    "category": "serial",
    "tag": "Sisterhood Drama",
    "networkTag": "ZEE TAMIL • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/mp.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "zee_anna",
    "serialCode": "anna",
    "title": "Anna",
    "tamilTitle": "அண்ணா",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "timeSlot": "10:00 PM",
    "episodes": "460+ Eps",
    "episodesCount": "460 episodes logged",
    "category": "serial",
    "tag": "Brotherhood Saga",
    "networkTag": "ZEE TAMIL • HIT",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/11/anku.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  }
];

// Available Reality Shows with Posters
export const COMPREHENSIVE_ALL_REALITY = [
  {
    "id": "reality_bigg_boss_10",
    "serialCode": "bigg_boss_10",
    "title": "Bigg Boss 10",
    "tamilTitle": "பிக் பாஸ் 10",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "networkTag": "VIJAY TV • PRIME SHOW",
    "genre": "Mega Reality",
    "timeSlot": "09:30 PM (Daily)",
    "episodes": "Season 10 Live",
    "episodesCount": "Daily Prime Episodes",
    "tag": "Prime Show",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2026/09/bbtamil.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#ef4444",
    "tamilColor": "#ef4444"
  },
  {
    "id": "reality_super_singer",
    "serialCode": "super_singer",
    "title": "Super Singer S10",
    "tamilTitle": "சூப்பர் சிங்கர் 10",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "genre": "Music Talent Show",
    "timeSlot": "Sat-Sun 06:30 PM",
    "episodesCount": "84 episodes logged",
    "tag": "Weekend Prime",
    "image": "https://arivumani.net/wp-content/uploads/2025/11/super-singer-230x150.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "reality_cooku_with_comali",
    "serialCode": "cooku_with_comali",
    "title": "Cooku with Comali S5",
    "tamilTitle": "குக் வித் கோமாளி 5",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "genre": "Culinary Comedy",
    "timeSlot": "Sat-Sun 08:00 PM",
    "episodesCount": "52 episodes logged",
    "tag": "Comedy Riot",
    "image": "https://arivumani.net/wp-content/uploads/2025/11/cooku-with-comali-230x150.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "reality_start_music",
    "serialCode": "start_music",
    "title": "Start Music",
    "tamilTitle": "ஸ்டார்ட் மியூசிக்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "genre": "Game Show",
    "timeSlot": "Sunday 08:00 PM",
    "episodesCount": "65 episodes logged",
    "tag": "Fun Game",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sm.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "reality_top_cooku",
    "serialCode": "top_cooku",
    "title": "Top Cooku Dupe Cooku",
    "tamilTitle": "டாப் குக் டூப் குக்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "genre": "Celebrity Cooking",
    "timeSlot": "Sunday 01:30 PM",
    "episodesCount": "42 episodes logged",
    "tag": "Sunday Special",
    "image": "https://arivumani.net/wp-content/uploads/2025/11/top-cooku-230x150.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "reality_super_samayal",
    "serialCode": "super_samayal",
    "title": "Super Samayal",
    "tamilTitle": "சூப்பர் சமையல்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "genre": "Traditional Cookery",
    "timeSlot": "Saturday 01:00 PM",
    "episodesCount": "140 episodes logged",
    "tag": "Cookery",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/supersamayal.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "reality_saregamapa",
    "serialCode": "saregamapa",
    "title": "Sa Re Ga Ma Pa S4",
    "tamilTitle": "ச ரி க ம ப 4",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "genre": "Vocal Showdown",
    "timeSlot": "Sat-Sun 07:00 PM",
    "episodesCount": "60 episodes logged",
    "tag": "Musical Gala",
    "image": "https://arivumani.net/wp-content/uploads/2025/11/saregamapa-230x150.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "reality_dance_jodi_dance",
    "serialCode": "dance_jodi_dance",
    "title": "Dance Jodi Dance",
    "tamilTitle": "டான்ஸ் ஜோடி டான்ஸ்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "genre": "Choreography Contest",
    "timeSlot": "Sat-Sun 08:30 PM",
    "episodesCount": "48 episodes logged",
    "tag": "Dance Battle",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2026/06/djd.webp",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "reality_super_mom",
    "serialCode": "super_mom",
    "title": "Super Mom",
    "tamilTitle": "சூப்பர் மாம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "genre": "Mothers & Kids Fun",
    "timeSlot": "Sunday 06:30 PM",
    "episodesCount": "36 episodes logged",
    "tag": "Family Special",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/supermom.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "reality_junior_super_stars",
    "serialCode": "junior_super_stars",
    "title": "Junior Super Stars",
    "tamilTitle": "ஜூனியர் சூப்பர் ஸ்டார்ஸ்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "genre": "Kids Talent Show",
    "timeSlot": "Sunday 04:30 PM",
    "episodesCount": "54 episodes logged",
    "tag": "Kids Acting Hunt",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/jss.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "reality_mr_mrs_chinnathirai",
    "serialCode": "mr_mrs_chinnathirai",
    "title": "Mr & Mrs Chinnathirai",
    "tamilTitle": "மிஸ்டர் & மிஸஸ் சின்னத்திரை",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "genre": "Celebrity Couple Game",
    "timeSlot": "Sunday 09:00 PM",
    "episodesCount": "95 episodes logged",
    "tag": "Couple Fun",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/mmc.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "reality_super_singer_junior",
    "serialCode": "super_singer_junior",
    "title": "Super Singer Junior",
    "tamilTitle": "சூப்பர் சிங்கர் ஜூனியர்",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "genre": "Kids Vocal Championship",
    "timeSlot": "Sat-Sun 06:30 PM",
    "episodesCount": "90 episodes logged",
    "tag": "Kids Music",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2026/05/ssj11.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  }
];

// Available TV Programmes with Posters
export const COMPREHENSIVE_ALL_PROGRAMMES = [
  {
    "id": "prog_neeya_naana",
    "serialCode": "neeya_naana",
    "title": "Neeya Naana",
    "tamilTitle": "நீயா நானா",
    "channel": "Star Vijay",
    "channelCode": "vijay",
    "genre": "Debate Talk Show",
    "timeSlot": "Sunday 12:30 PM",
    "episodesCount": "820 episodes logged",
    "tag": "Debate Gala",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/nn.jpg",
    "bgColor": "#1e1b4b",
    "borderColor": "#818cf8",
    "tamilColor": "#818cf8"
  },
  {
    "id": "prog_tamizha_tamizha",
    "serialCode": "tamizha_tamizha",
    "title": "Tamizha Tamizha",
    "tamilTitle": "தமிழா தமிழா",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "genre": "Debate Forum",
    "timeSlot": "Sunday 12:00 PM",
    "episodesCount": "340 episodes logged",
    "tag": "Debate Show",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/tt.webp",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  },
  {
    "id": "prog_vanakkam_tamizha",
    "serialCode": "vanakkam_tamizha",
    "title": "Vanakkam Tamizha",
    "tamilTitle": "வணக்கம் தமிழா",
    "channel": "Sun TV",
    "channelCode": "sun",
    "genre": "Morning Live Show",
    "timeSlot": "Daily 08:00 AM",
    "episodesCount": "1950 episodes logged",
    "tag": "Celebrity Talk",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/vt.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "prog_sunday_kondattam",
    "serialCode": "sunday_kondattam",
    "title": "Sunday Kondattam",
    "tamilTitle": "சண்டே கொண்டாட்டம்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "genre": "Sunday Variety Show",
    "timeSlot": "Sunday 09:30 AM",
    "episodesCount": "210 episodes logged",
    "tag": "Entertainment",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/sk.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "prog_cine_mini",
    "serialCode": "cine_mini",
    "title": "Cine Mini",
    "tamilTitle": "சினி மினி",
    "channel": "Sun TV",
    "channelCode": "sun",
    "genre": "Cinema Buzz",
    "timeSlot": "Saturday 11:00 AM",
    "episodesCount": "480 episodes logged",
    "tag": "Kollywood",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/cm.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "prog_natchathira_kondattam",
    "serialCode": "natchathira_kondattam",
    "title": "Natchathira Kondattam",
    "tamilTitle": "நட்சத்திர கொண்டாட்டம்",
    "channel": "Sun TV",
    "channelCode": "sun",
    "genre": "Celebrity Carnival",
    "timeSlot": "Festive Special",
    "episodesCount": "80 episodes logged",
    "tag": "Stars Special",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/snk.jpg",
    "bgColor": "#172033",
    "borderColor": "#38bdf8",
    "tamilColor": "#38bdf8"
  },
  {
    "id": "prog_olimayamana_ethirkalam",
    "serialCode": "olimayamana_ethirkalam",
    "title": "Olimayamana Ethirkalam",
    "tamilTitle": "ஒளிமயமான எதிர்காலம்",
    "channel": "Zee Tamil",
    "channelCode": "zee",
    "genre": "Morning Astrology & Lifestyle",
    "timeSlot": "Daily 07:00 AM",
    "episodesCount": "1800 episodes logged",
    "tag": "Morning Show",
    "image": "https://www.tamildhool.tech/wp-content/uploads/2025/07/oe.jpg",
    "bgColor": "#2a122e",
    "borderColor": "#c084fc",
    "tamilColor": "#c084fc"
  }
];

// Special Events (Empty - omitted from home screen index per requirements)
export const COMPREHENSIVE_ALL_EVENTS = [];

/**
 * Scrape episode stream from active server using metadata query
 * Format Server 1: "Kayal | 26-09-2026 |"
 * Format Server 2: "Kayal 22-09-2026"
 */
export async function scrapeEpisodeStreamWithMetadata(metadataQuery, serialObj, dateStr, serverId = 'tamildhool') {
  let title = serialObj?.title || 'Kayal';
  let queryDate = dateStr || '26-09-2026';
  let channel = (serialObj?.channel || 'Sun TV').replace(/Serial|Show|Programme/gi, '').trim();

  if (metadataQuery) {
    if (metadataQuery.includes('|')) {
      const parts = metadataQuery.split('|').map(s => s.trim()).filter(Boolean);
      if (parts[0]) title = parts[0];
      if (parts[1]) queryDate = parts[1];
      if (parts[2]) channel = parts[2].replace(/Serial|Show|Programme/gi, '').trim();
    } else {
      const dateMatch = metadataQuery.match(/\b\d{2}-\d{2}-\d{4}\b/);
      if (dateMatch) {
        queryDate = dateMatch[0];
        title = metadataQuery.replace(dateMatch[0], '').replace(/\|/g, '').trim();
      } else {
        title = metadataQuery.replace(/\|/g, '').trim();
      }
    }
  }

  const { TamilDhool } = await import('../providers/tamildhool/TamilDhoolProvider.js');
  const { TamilGun, REQUIRED_PLAYALLU_HEADERS } = await import('../providers/tamilgun/TamilGunProvider.js');

  // 1. If Server 2 (TamilGun / Arivumani)
  if (serverId === 'tamilgun') {
    try {
      const res = await TamilGun.findEpisodeByDate(title, queryDate, channel);
      if (res && res.streamUrl) {
        return {
          streamUrl: res.streamUrl,
          headers: res.headers || REQUIRED_PLAYALLU_HEADERS,
          referer: res.headers?.Referer || 'https://play.playallu.xyz/',
          matchedTitle: res.matchedTitle || `${title} ${queryDate}`,
          server: 'Server 2',
          status: 'success'
        };
      }
    } catch (e) {
      console.warn('[TvSerialsLiveScraper] Server 2 error:', e.message);
    }
  }

  // 2. If Server 1 (Tamildhool)
  try {
    const res = await TamilDhool.findEpisodeByDate(title, queryDate, channel);
    const resolvedUrl = res?.streamUrl || res?.bestStream?.url || res?.details?.links?.[0]?.url;
    if (res && resolvedUrl) {
      return {
        streamUrl: resolvedUrl,
        headers: res.headers || { Referer: 'https://tamildhool.tech/' },
        referer: res.headers?.Referer || res.headers?.referer || 'https://tamildhool.tech/',
        matchedTitle: res.matchedTitle || res.title || res.post?.title || `${title} | ${queryDate} |`,
        server: 'Server 1',
        status: 'success'
      };
    }
  } catch (e) {
    console.warn('[TvSerialsLiveScraper] Server 1 error:', e.message);
  }

  // 3. Fallback to Server 2 if Server 1 had no stream
  if (serverId !== 'tamilgun') {
    try {
      const res = await TamilGun.findEpisodeByDate(title, queryDate, channel);
      if (res && res.streamUrl) {
        return {
          streamUrl: res.streamUrl,
          headers: res.headers || REQUIRED_PLAYALLU_HEADERS,
          referer: res.headers?.Referer || 'https://play.playallu.xyz/',
          matchedTitle: res.matchedTitle || `${title} ${queryDate}`,
          server: 'Server 2',
          status: 'success'
        };
      }
    } catch (e) {}
  }

  // 4. No sandbox HLS link! Return null so player displays clean playback error
  return {
    streamUrl: null,
    headers: null,
    referer: null,
    matchedTitle: serverId === 'tamilgun' ? `${title} ${queryDate}` : `${title} | ${queryDate} |`,
    server: serverId === 'tamilgun' ? 'Server 2' : 'Server 1',
    status: 'error'
  };
}
